### ISSUE TITLE
У меня ошибка, не могу нагуглить, помоги пожалуйста

### ISSUE THREAD

**Issue by sirok1** [sanichyut/discordbot#1]
у меня ошибка, не могу понять, как исправить, можете помочь ? 
TypeError: Cannot read property 'memberCount' of undefined
    at change (C:\Users\Sanya\Desktop\discordbot-master\main.js:81:64)
    at Timeout._onTimeout (C:\Users\Sanya\Desktop\discordbot-master\main.js:85:42)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
    
   
C:\Users\Sanya\Desktop\discordbot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133
    const invalidToken = new DJSError(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\Sanya\Desktop\discordbot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\Sanya\Desktop\discordbot-master\node_modules\discord.js\src\client\Client.js:222:21) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

**Comment by prosko123** [comment]
а ты открыл install bat когда закачаешь должно все ити по маслу

**Comment by sirok1** [comment]
> а ты открыл install bat когда закачаешь должно все ити по маслу
Во время очень конечно, ссори что не закрыл, проблема решилась ещё два года назад тем что я своего бота написал
